name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/book-network-ui/package-lock.json

      - name: Debug directory
        run: ls -R book-network-ui || dir book-network-ui
        shell: bash

      - name: Install dependencies
        run: cd book-network-ui && npm ci

      - name: Build Angular app
        run: cd book-network-ui && npm run build --prod

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./book-network-ui
          file: ./docker/frontend/Dockerfile
          push: true
          tags: |
            docker.io/hayet22/book-network-ui:${{ github.sha }}
            docker.io/hayet22/book-network-ui:latest